apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins_test
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins_test
  template:
    metadata:
      labels:
        app: jenkins_test
    spec:
      containers:
      - name: jenkins_test
        image: jenkins/jenkins
        ports:
        - containerPort: 60000